# Conjugate Gradients with operators

Written by H. Tagare 2/8/2024

The operators are defined in the folder optlib
The CG algorithm is defined in the folder c_grad
Both have to imported to get everything to work

In [1]:
import numpy as np
import optlib.operators as op
import optlib.c_grad as cg

### Test 1: Simple test without noise
#### The operator A is (MO+R). Task is to recover a vector. No regularization on CG

In [2]:
M=op.matrix_op(np.array(((1, 2, 3),(0, 1, 0),(2, 3,1))))
O=op.scalar_prod_op(2.0)
R=op.scalar_prod_op(0.1)
A=op.add_op(op.composite_op(M,O),R) 

x=np.array((1,0.5,1)).reshape(-1,1) #Input x
y=A.forward(x) #Create noiseless output by applying A
print(f"x={x}\n y={y}")

x0=np.zeros_like(x) #Initial value for CG
x,flag=cg.c_grad(y,A,x0)
print(f"x={x} \n flag={flag}")

x=[[1. ]
 [0.5]
 [1. ]]
 y=[[10.1 ]
 [ 1.05]
 [ 9.1 ]]
CG: step=1 res_norm=3.234651420766811 
CG: step=2 res_norm=0.748020413188572 
CG: step=3 res_norm=6.937076823812195e-12 
x=[[1. ]
 [0.5]
 [1. ]] 
 flag=False


### Test 2: x is matrix, y contains noise, CG uses regularizer

In [3]:
M=op.matrix_op(np.array(((1, 2, 3),(0, 1, 0),(2, -3,1))))
O=op.scalar_prod_op(2.0)
R=op.scalar_prod_op(0.1)

A=op.add_op(op.composite_op(M,O),R)

x=np.transpose(np.array(((1,0.5,1),(0,1,0))))
y=A.forward(x)
y=y+0.1*np.random.normal(size=y.shape)
print(f"x={x}\n y={y}")

x0=np.zeros_like(x)
x,flag=cg.c_grad(y,A,x0,B=R,f_tol=1e-6)
print(f"x={x} \n flag={flag}")


x=[[1.  0. ]
 [0.5 1. ]
 [1.  0. ]]
 y=[[10.14141833  4.02264302]
 [ 1.07436577  1.89952873]
 [ 3.04766637 -6.06001173]]
CG: step=1 res_norm=8.254723011626185 
CG: step=2 res_norm=0.22491730966324167 
CG: step=3 res_norm=2.430661817612657e-13 
x=[[ 0.99859343 -0.23758606]
 [ 0.50863263  0.90420706]
 [ 1.00147787  0.15069718]] 
 flag=False


### CG with fft

In [4]:
x=np.random.normal(size=(4,4))
print(x)
A=op.real_fftn_op()
y=A.forward(x)
y=y+0.2*np.random.normal(size=y.shape)
#print(f"x={x}\n y={y}")
print(f"x={x}")

x0=np.zeros_like(x)
R=op.scalar_prod_op(0.1)
x,_=cg.c_grad(y,A,x0,B=R)
print(x)

[[-9.35137089e-01  5.79303245e-01 -7.69235386e-01 -1.27389900e+00]
 [ 1.44953619e+00 -4.23690306e-01  1.76574292e+00 -9.97186553e-04]
 [ 3.26783388e-01 -2.13127184e+00 -6.31862366e-01 -8.58911648e-01]
 [ 1.07452299e-01 -5.27870612e-01 -1.12172214e-01 -4.12477654e-01]]
x=[[-9.35137089e-01  5.79303245e-01 -7.69235386e-01 -1.27389900e+00]
 [ 1.44953619e+00 -4.23690306e-01  1.76574292e+00 -9.97186553e-04]
 [ 3.26783388e-01 -2.13127184e+00 -6.31862366e-01 -8.58911648e-01]
 [ 1.07452299e-01 -5.27870612e-01 -1.12172214e-01 -4.12477654e-01]]
CG: step=1 res_norm=6.8047181790166545e-16 
[[-0.98088528  0.55882305 -0.78848974 -1.27603066]
 [ 1.37903318 -0.39160353  1.79012039  0.00363904]
 [ 0.2318761  -2.09983246 -0.64560146 -0.84006989]
 [ 0.05023724 -0.51801781 -0.06920153 -0.38050189]]
